SSUChallengers/Findog_Server

.gitignore, src/main/java/challengers/findog/config/secret/Secret.java, src/main/resources/application.yml
- /src/main/java/challengers/findog/config/secret/
- /src/main/resources/
위 두 디렉토리 내의 파일 트래킹 종료
=> [docs] .gitignore 파일 수정

build.gradle, src/main/java/challengers/findog/utils/s3Component/AwsS3ControlService.java, src/main/java/challengers/findog/utils/s3Component/ControlService.java, src/main/java/challengers/findog/utils/s3Component/FileControlService.java
- 파일 등록 / 삭제 기능 구현
- 프로필 사진 등록, 수정, 삭제
- 게시글 등록, 수정, 삭제 
위의 기능 구현에 필요한 이미지 파일을 받아 S3 bucket에 업로드/삭제 하는 기능을 구현했습니다.
* resoures 디렉토리 내의 s3 접근을 위한 설정 저장 파일(.yml) 생성 후에 실행해야 합니다.
=> [Feat] AWS Cloud S3 파일 업로드/삭제 기능 구현

src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/config/Constant.java, src/main/java/challengers/findog/src/user/UserController.java, src/main/java/challengers/findog/src/user/UserRepository.java, src/main/java/challengers/findog/src/user/UserService.java, src/main/java/challengers/findog/src/user/model/PostSignUpReq.java, src/main/java/challengers/findog/src/user/model/PostSignUpRes.java, src/main/java/challengers/findog/src/user/model/User.java, src/main/java/challengers/findog/utils/ValidationRegex.java
- 이메일(email) 
- 중복 검사 수행
- 닉네임(nickname) 
- 중복 검사 수행
- 1-15자 
- 한글,영어,숫자로만 구성 가능 
- 비밀번호(password) 
- 8~20글자
- 특수문자, 숫자, 영어 1자 이상 포함
- 핸드폰 번호(phoneNum)
- 번호 형식 확인 
- 프로필 사진(profileImg) 
- .jpg || . jpeg || .png || .bmp 확장자 파일만 가능
- userId, userJWT 반환
=> [Feat] 회원가입 기능 구현

src/main/java/challengers/findog/src/user/UserController.java, src/main/java/challengers/findog/src/user/UserService.java, src/main/java/challengers/findog/utils/ValidationRegex.java
- 닉네임 입력 여부 확인
- 닉네임 형식 확인
성공 시 return "사용 가능 닉네임입니다."
=> [Feat] 닉네임 중복 확인 기능 구현

src/main/java/challengers/findog/src/user/UserController.java, src/main/java/challengers/findog/src/user/UserService.java
- 이메일 빈 값 넘어온 경우
- 이메일 형식에 맞지 않는 경우
사용 가능한 이메일인 경우에만 성공 코드 반환
=> [Feat] 이메일 중복 확인 기능 구현

src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/src/user/UserController.java, src/main/java/challengers/findog/src/user/UserRepository.java, src/main/java/challengers/findog/src/user/UserService.java, src/main/java/challengers/findog/src/user/model/PostLoginReq.java, src/main/java/challengers/findog/src/user/model/PostLoginRes.java
- 이메일 입력 확인
- 이메일 형식 확인
- 비밀번호 입력 확인
- 이메일을 사용해 유저 존재 여부 확인
-  userId
-  userJWT
-  profileImgUrl
=> [Feat] 로그인 기능 구현

src/main/java/challengers/findog/src/user/UserController.java, src/main/java/challengers/findog/src/user/UserService.java
- X-ACCESS-TOKEN (JWT token)
- userId
- userJWT
- profileImgUrl
=> [Feat] 자동 로그인 기능 구현

src/main/java/challengers/findog/src/user/UserController.java, src/main/java/challengers/findog/src/user/UserService.java, src/main/java/challengers/findog/src/user/model/PatchLeaveReq.java
- 기존 userId 넘겨주는 방식으로 구현 -> JWT token 넘겨주면 userId 읽어와서 사용하는 방식으로 변경
=> [Refactor] 회원 탈퇴 기능 JWT 사용 수정

src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/src/comment/CommentController.java, src/main/java/challengers/findog/src/comment/CommentRepository.java, src/main/java/challengers/findog/src/comment/CommentService.java, src/main/java/challengers/findog/src/comment/model/Comment.java, src/main/java/challengers/findog/src/comment/model/GetCommentRes.java, src/main/java/challengers/findog/src/comment/model/PostCommentReq.java
- JWT token 필수
- 일반 댓글의 경우, parentCommentId = 0
- 댓글의 대댓글인 경우, parentCommentId = {댓글 Id}
- ex ) commentId = 2인 댓글의 대댓글을 작성하려면 parentCommentId = 2
- Swagger UI 추가 설정 예정
=> [Feat] 댓글 등록 기능 구현

src/main/java/challengers/findog/src/comment/CommentController.java, src/main/java/challengers/findog/src/comment/CommentService.java
1. Query String으로 postId 받음
2. 해당 postId에 맞는 게시글의 댓글들 모두 반환
3. swagger 설정 완료
=> [Feat] 댓글 조회 기능 구현

src/main/java/challengers/findog/src/comment/CommentService.java
- 댓글 등록 API
- 댓글 수정 API
=> getCommentList() 사용하도록 수정
=> [Refactor] 댓글 관련 기능 코드 수정

src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/src/mypage/MypageController.java, src/main/java/challengers/findog/src/mypage/MypageRepository.java, src/main/java/challengers/findog/src/mypage/MypageService.java, src/main/java/challengers/findog/src/mypage/model/PatchUserInfoReq.java, src/main/java/challengers/findog/src/user/UserService.java, src/main/java/challengers/findog/src/user/model/User.java
=> [feat] 회원정보 수정 기능 구현

src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/src/board/BoardController.java, src/main/java/challengers/findog/src/board/BoardRepository.java, src/main/java/challengers/findog/src/board/BoardService.java, src/main/java/challengers/findog/src/board/model/PostBoardReq.java, src/main/java/challengers/findog/src/board/model/PostBoardRes.java
- 게시글 작성 구현(이미지 다중선택 가능, 없어도 무방)
=> [feat] 게시글 작성 구현

src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/src/board/BoardController.java, src/main/java/challengers/findog/src/board/BoardRepository.java, src/main/java/challengers/findog/src/board/BoardService.java, src/main/java/challengers/findog/src/board/model/PatchBoardReq.java, src/main/java/challengers/findog/src/mypage/MypageService.java
=> [Refactor] 게시글 수정 구현 개선

src/main/java/challengers/findog/config/WebMvcConfig.java, src/main/java/challengers/findog/src/WebSecurityConfig.java, src/main/java/challengers/findog/src/board/BoardController.java, src/main/java/challengers/findog/src/comment/CommentController.java, src/main/java/challengers/findog/src/mypage/MypageController.java, src/main/java/challengers/findog/src/user/UserController.java
=> [Fix] CORS 문제 port 수정

src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/src/board/BoardController.java, src/main/java/challengers/findog/src/board/BoardRepository.java, src/main/java/challengers/findog/src/board/BoardService.java, src/main/java/challengers/findog/src/board/model/DeleteBoardReq.java, src/main/java/challengers/findog/src/board/model/GetBoardRes.java, src/main/java/challengers/findog/src/board/model/PatchBoardReq.java
- 게시글 삭제 구현
- 해당 게시글의 이미지도 함께 삭제(s3 및 서버)
**todo**
- 해당 게시글의 댓글 함께 삭제
=> [Feat] 게시글 삭제 구현

src/main/java/challengers/findog/config/WebMvcConfig.java
=> [fix] cors 해결 위한 port 추가

src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/src/board/BoardController.java, src/main/java/challengers/findog/src/board/BoardRepository.java, src/main/java/challengers/findog/src/board/BoardService.java, src/main/java/challengers/findog/src/board/model/DeleteBoardReq.java, src/main/java/challengers/findog/src/board/model/GetBoardRes.java, src/main/java/challengers/findog/src/board/model/PatchBoardReq.java, src/main/java/challengers/findog/src/board/model/PostBoardReq.java
- 실질적인 imgFile이 없더라도 request body의 필드값으로는 들어가야게끔 수정완료
=> [Fix] 게시판 작성 imgFile 오류 수정

src/main/java/challengers/findog/src/board/BoardController.java, src/main/java/challengers/findog/src/board/BoardRepository.java, src/main/java/challengers/findog/src/board/BoardService.java, src/main/java/challengers/findog/src/board/model/Board.java, src/main/java/challengers/findog/src/board/model/GetBoardRes.java
- 게시글 정보 가져오기
- 게시글 이미지 리스트 가져오기
- 로그인 유저 좋아요 여부 가져오기
- todo 댓글 리스트 가져오기
=> [Feat] 게시글 조회 구현

src/main/java/challengers/findog/src/board/BoardController.java, src/main/java/challengers/findog/src/board/BoardRepository.java, src/main/java/challengers/findog/src/board/BoardService.java, src/main/java/challengers/findog/src/board/model/Board.java, src/main/java/challengers/findog/src/board/model/Criteria.java, src/main/java/challengers/findog/src/board/model/Paging.java
- 게시글 조회 postId, thumbnail 추가
- likeCount, commentCount 타입 수정
(primitive type->reference type) : null값 오류 해결
- 게시글 리스트 페이징 처리 완료
(default page=1, size=5)
=> [feat] 게시물 리스트 구현

src/main/java/challengers/findog/src/board/BoardController.java, src/main/java/challengers/findog/src/board/BoardRepository.java, src/main/java/challengers/findog/src/board/BoardService.java
- 검색어 입력 시, 제목 또는 내용에 포함된 검색어라면 조회
- 페이징 처리 완료
=> [feat] 게시물 검색 구현

src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/src/comment/CommentService.java, src/main/java/challengers/findog/src/mypage/MypageController.java, src/main/java/challengers/findog/src/mypage/MypageRepository.java, src/main/java/challengers/findog/src/mypage/MypageService.java, src/main/java/challengers/findog/src/mypage/model/PatchNicknameReq.java, src/main/java/challengers/findog/src/user/UserService.java
=> [feat] 닉네임 수정 기능 구현

src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/src/mypage/MypageController.java, src/main/java/challengers/findog/src/mypage/MypageRepository.java, src/main/java/challengers/findog/src/mypage/MypageService.java, src/main/java/challengers/findog/src/mypage/model/PatchPhoneNumReq.java
=> [feat] 핸드폰 번호 수정 기능 구현

src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/src/mypage/MypageController.java, src/main/java/challengers/findog/src/mypage/MypageRepository.java, src/main/java/challengers/findog/src/mypage/MypageService.java, src/main/java/challengers/findog/src/mypage/model/GetCheckUserReq.java, src/main/java/challengers/findog/src/mypage/model/PatchPasswordReq.java
- flow
- 비밀번호 수정 전 유저 확인 API 호출
-  비밀번호 수정 API 호출
- 둘 API 모두 JWT 필요
=> [feat] 비밀번호 수정 기능 구현

build.gradle, src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/src/animal/AnimalController.java, src/main/java/challengers/findog/src/animal/AnimalRepository.java, src/main/java/challengers/findog/src/animal/AnimalService.java, src/main/java/challengers/findog/src/animal/OpenApiController.java, src/main/java/challengers/findog/src/animal/model/Animal.java
- openApi 자동 호출하여 공고 업데이트 하는 기능 추가 필요
=> [feat] 유기동물 공고 DB 저장 기능 구현

src/main/java/challengers/findog/config/BaseResponseStatus.java, src/main/java/challengers/findog/src/user/UserController.java, src/main/java/challengers/findog/src/user/UserService.java, src/main/java/challengers/findog/src/user/model/GetUserRes.java
- path variable로 userId
- JWT 필요
=> [feat] 유저 정보 조회 기능 구현

src/main/java/challengers/findog/src/animal/AnimalRepository.java, src/main/java/challengers/findog/src/animal/AnimalService.java, src/main/java/challengers/findog/src/animal/model/Animal.java
=> [fix] 유기동물 공도 DB 저장 필드 추가

src/main/java/challengers/findog/src/mypage/MypageController.java
=> [fix] 유저 확인 기능 http method post로 수정

src/main/java/challengers/findog/src/board/BoardController.java, src/main/java/challengers/findog/src/board/BoardRepository.java
- keyword default value = ""로 설정하여 전체 게시글 수 조회와 검색어 조회 모두 가능하게 수정
=> [fix] 검색어 입력 시 총 게시글 수 조회 오류 수정

src/main/java/challengers/findog/src/board/BoardController.java, src/main/java/challengers/findog/src/board/BoardRepository.java, src/main/java/challengers/findog/src/board/BoardService.java
- 키워드로 검색
- 지역, 카테고리 필터링 검색
- 기간 설정
- 정렬: 최신순, 조회수순, 좋아요순
=> [feat] 게시물 필터링 검색 구현

src/main/java/challengers/findog/config/WebMvcConfig.java
=> [fix] cors 추가

src/main/java/challengers/findog/src/animal/AnimalController.java, src/main/java/challengers/findog/src/animal/AnimalRepository.java, src/main/java/challengers/findog/src/animal/AnimalService.java
- int page => 검색할 페이지 default = 1
- int size => 검색할 페이지에 보여줄 공고 개수 default = 6
- String word => 검색창에 입력한 단어 (입력 선택 가능) 
- region => 지역 (입력 선택 가능)
- category => 개, 고양이, 기타 (입력 선택 가능)
- breed => category의 세부 종 (입력 선택 가능)
- status => 보호중, 종료 (입력 선택 가능)
=> [feat] 유기동물 검색 기능 구현

src/main/java/challengers/findog/src/animal/AnimalService.java
=> [fix] 유기동물 공고 검색 기능 에러 수정

src/main/java/challengers/findog/FindogApplication.java, src/main/java/challengers/findog/src/animal/AnimalRepository.java, src/main/java/challengers/findog/src/animal/OpenApiController.java
=> [feat] 유기동물 공고 자동 업데이트 기능 구현
